-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [fold_arity]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

namespace fold_arity

/- [fold_arity::compute_log_arity_for_round]:
   Source: 'src/lib.rs', lines 8:0-30:1 -/
def compute_log_arity_for_round
  (log_current_height : Std.Usize) (next_input_log_height : Option Std.Usize)
  (log_final_height : Std.Usize) (max_log_arity : Std.Usize) :
  Result Std.Usize
  := do
  let max_fold_to_target ← log_current_height - log_final_height
  let max_fold ←
    match next_input_log_height with
    | none => ok max_fold_to_target
    | some next_log_height =>
      let max_fold_to_next ← log_current_height - next_log_height
      if max_fold_to_next < max_fold_to_target
      then ok max_fold_to_next
      else ok max_fold_to_target
  if max_fold < max_log_arity
  then ok max_fold
  else ok max_log_arity

end fold_arity
